[ERROR][2013-01-23 10:27:00]-[ 653ad6480000000a:17328 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 653ad6480000000a:17328 ]java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at com.hola.tarbs.service.execution.Del_InsertForBs.createDel(Del_InsertForBs.java:70)
	at com.hola.tarbs.service.execution.Del_InsertForBs.sqlCreate(Del_InsertForBs.java:23)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:358)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-23 10:36:30]-[ 654387810000000a:1765 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 654387810000000a:1765 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa4f (INSTNO,HHTACT,HHTVND,HHTVNM,HHTVTP,HHTVTN,HHTVCR,HHTVCN,HHTVF1,HHTVF2,HHTVF3,HHTVF4,HHTVA1,HHTVA2) values ('654387810000010a' , 'C' , '099998' , 'Dumy Vendor虚拟厂商' , '3' , 'DCVENDORS' , 'RMB' , '人民币' , '2' , null , 'N' , 'Y' , 'Dumy Vendor虚拟厂商' , null)]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'HHTACT' in 'field list'
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'HHTACT' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 12 more
[ERROR][2013-01-23 11:30:47]-[ 657537d70000000a:14953 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 657537d70000000a:14953 ]org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [ insert into hht13101.htoa3f (INSTNO,HHTSKU,HHTUPT,HHTUPC) values ('5fe60259000001a9' , '000024556' , 'A' , null)]; Column 'HHTUPC' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'HHTUPC' cannot be null
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:69)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'HHTUPC' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-23 13:51:32]-[ 65f6123b0000000a:13078 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 65f6123b0000000a:13078 ]org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [ insert into hht13101.htoa3f (INSTNO,HHTSKU,HHTUPT,HHTUPC) values ('5fe60259000001a9' , '000024556' , 'A' , null)]; Column 'HHTUPC' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'HHTUPC' cannot be null
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:69)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'HHTUPC' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 12 more
[ERROR][2013-01-23 13:56:11]-[ 65fa554b0000000a:2562 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 65fa554b0000000a:2562 ]org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [ insert into hht13101.htoa3f (INSTNO,HHTSKU,HHTUPT,HHTUPC) values ('5fe60259000001a9' , '000024556' , 'A' , null)]; Column 'HHTUPC' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'HHTUPC' cannot be null
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:69)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'HHTUPC' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 12 more
[ERROR][2013-01-23 17:47:16]-[ 66cc00c50000000a:166234 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 66cc00c50000000a:166234 ]java.lang.ArrayIndexOutOfBoundsException: 18
	at com.hola.tarbs.service.execution.Del_InsertForBs.createInsert(Del_InsertForBs.java:52)
	at com.hola.tarbs.service.execution.Del_InsertForBs.sqlCreate(Del_InsertForBs.java:31)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:358)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
